ContactUs and PrivacyPolicy
UladzislauPapliouka/ModsenClientBlog pull request #1
Opened 2023-05-12 07:02 UTC by UladzislauPapliouka

2023-05-12 08:56 UTC, anyaprystavka requested changes

2023-05-12 08:56 UTC, anyaprystavka commented on .eslintignore
> +fileTransformer.js
Нужно в пр смотреть, чтобы в файле всегда была пустая строка в конце файла, таким образом может выдавать ошибку. Это настройка prettier, иногда происходит из-за того, что разные ОС используются, но настраивать это нужно.

2023-05-12 08:56 UTC, anyaprystavka commented on .github/workflows/runTests.yml
> +  push:
добавь еще проверку на pull-request, часто встречается

2023-05-12 08:56 UTC, anyaprystavka commented on src/components/Header/index.tsx
> +          handleClose={() => {
дублирование кода в обработчиках событий, можно вынести в одну функцию смену состояния

2023-05-12 08:56 UTC, anyaprystavka commented on src/pages/_app.tsx
> +      <Link href="/blog">Blog</Link>
тоже не забываем про принцип DRY везде, роуты в константу выносим

2023-05-12 08:56 UTC, anyaprystavka commented on src/pages/_app.tsx
> +        <Typography variant="head4">Video about us</Typography>
можно уже подключать локализацию на странице

2023-05-12 08:56 UTC, anyaprystavka commented on src/components/CustomSelect/index.tsx
> +  const selectRef = useRef(null);
хуки выше в компоненте должны находиться

2023-05-12 08:56 UTC, anyaprystavka commented on src/components/Footer/index.tsx
> +  const emailSchema = string().test(
вот это лучше вынести куда-нибудь, просто в функцию ту же, громоздко получается

2023-05-12 08:56 UTC, anyaprystavka commented on src/components/Footer/index.tsx
> +        process.env.NEXT_PUBLIC_SERVICE_ID as string,
также переменные, которые берутся из .env файла можно вынести в объект, чтобы также сократить код при использовании переменных

2023-05-12 08:56 UTC, anyaprystavka commented on src/components/Footer/index.tsx
> +        <Link href="/">Home</Link>
map

2023-05-12 08:56 UTC, anyaprystavka commented on src/components/Footer/index.tsx
> +        <Link href="/">Home</Link>
просто в config выноси

2023-05-12 08:56 UTC, anyaprystavka commented on src/components/SocialWrapper/index.tsx
> +    <FacebookIcon />
иконки не валидные(нужно сделать реализацию перехода по ссылке в новом окне)

2023-05-12 08:56 UTC, anyaprystavka commented on src/components/Modal/index.tsx
> +      if (window.innerWidth >= 1040) {
в константу брейкпоинты

2023-05-12 08:56 UTC, anyaprystavka commented on src/components/SelectItemsList/index.tsx
> +          ((option: T) => {
вот тут не создавать функцию, а вынеси её выше и передавай в нее option

2023-05-12 08:56 UTC, anyaprystavka commented on src/components/TextArea/index.tsx
> +    <textarea
а почему textarea выносил? он переиспользуется? или же дело в обработке невалидного введенного значения?

2023-05-12 08:56 UTC, anyaprystavka commented on src/components/TextArea/index.tsx
> +  value?: string | undefined;
а value  в компоненте не используется нигде

2023-05-12 08:56 UTC, anyaprystavka commented on src/pages/privacy/index.tsx
> +        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
вот такие текста однозначно выносятся в константу(config)

2023-05-12 08:56 UTC, anyaprystavka commented on .eslintignore
> +fileTransformer.js
везде это надо пересмотреть

2023-05-12 08:56 UTC, anyaprystavka commented on .github/workflows/runTests.yml
> +    runs-on: ubuntu-latest
проверяй установку зависимостей, билд приложения, тесты, eslint, prettier

2023-05-12 08:56 UTC, anyaprystavka commented on src/pages/contact/index.tsx
> +import { Map, Marker } from 'pigeon-maps';
неправильный порядок импортов
если подключен simple-import-sort, то как он работает?

2023-05-12 08:56 UTC, anyaprystavka commented on src/pages/contact/index.tsx
> +    name: '',
почитай про принцип конечного автомата, может будут идеи как это реализовать иначе

2023-05-12 08:56 UTC, anyaprystavka commented on src/components/Footer/index.tsx
> +  const handleClick = (event: SyntheticEvent<HTMLButtonElement>) => {
если где-то форма будет переиспользована, то выноси в хук кастомный отдельно все

2023-05-13 07:56 UTC, UladzislauPapliouka commented on src/components/TextArea/index.tsx
> +  value?: string | undefined;
Оно используется, оно остаётся в  `...props` и передаётся `textarea`

2023-05-13 09:02 UTC, UladzislauPapliouka commented on src/components/TextArea/index.tsx
> +    <textarea
Выносил из-за дизайна, и обертки с ошибкой

2023-05-13 09:07 UTC, UladzislauPapliouka commented on src/components/SelectItemsList/index.tsx
> +          ((option: T) => {
Изменил немного, но вынести выше всё равно не выходит

2023-05-13 09:13 UTC, UladzislauPapliouka commented on src/components/Footer/index.tsx
> +  const handleClick = (event: SyntheticEvent<HTMLButtonElement>) => {
Не будет

2023-05-18 18:59 UTC, UladzislauPapliouka commented on src/components/Footer/index.tsx
> +  const emailSchema = string().test(
Переделала на Formik

2023-05-18 19:19 UTC, UladzislauPapliouka commented on src/pages/contact/index.tsx
> +    name: '',
Заменил на Formik

2023-05-18 19:27 UTC, UladzislauPapliouka commented on src/pages/_app.tsx
> +        <Typography variant="head4">Video about us</Typography>
Пока разбираюсь с ней, добавлю в некст пр

2023-05-19 08:34 UTC, anyaprystavka requested changes

2023-05-19 08:34 UTC, anyaprystavka commented on src/components/ErrorBoundaries/errorBoudaries.module.scss
> +    font-size: 40px;
Не вынесено в тему

2023-05-19 08:34 UTC, anyaprystavka commented on src/components/ErrorBoundaries/errorBoudaries.module.scss
> +    font-size: 20px;
Не вынесено в тему

2023-05-19 08:34 UTC, anyaprystavka commented on src/components/Input/input.module.scss
> +    padding: 14px 25px;
Не вынесено в тему

2023-05-19 08:34 UTC, anyaprystavka commented on src/components/Input/input.module.scss
> +      border: 2px solid red;
цвет не вынесен в тему

2023-05-19 08:34 UTC, anyaprystavka commented on src/components/SelectItemsList/selectItemsList.module.scss
> +    z-index: 1;
z-index не вынесен в тему

2023-05-19 08:34 UTC, anyaprystavka commented on src/components/TextArea/input.module.scss
> +      border: 2px solid red;
цвет не вынесен в тему

2023-05-19 08:34 UTC, anyaprystavka commented on src/containers/ContentContainer/contentContainer.module.scss
> +    padding: 18px 80px 18px 80px;
не вынесено в тему

2023-05-19 08:53 UTC, merged